export const UPDATE_EMAIL_FIELD = "UPDATE_EMAIL_FEILD";
export const EMAIL_ERROR = "EMAIL_ERROR";

export const UPDATE_PASSWORD_FIELD = "UPDATE_PASSWORD_FIELD";
export const PASSWORD_ERROR = "PASSWORD_ERROR";

export const UPDATE_REPASSWORD_FIELD = "UPDATE_REPASSWORD_FIELD";
export const REPASSWORD_ERROR = "REPASSWORD_ERROR";

export const FIREBASE_ERROR = "FIREBASE_ERROR";

export const PASSWORD_RESET_LINK_SENT = "PASSWORD_RESET_LINK_SENT";

export const HAS_USER_REGISTERED = "HAS_USER_REGISTERED";
export const VALID_USER = " VALID_USER";
export const EMAIL_PATTERN = /^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/;
